# https://www.jetbrains.com/help/pycharm/http-client-in-product-code-editor.html

### GET Hello World
GET http://127.0.0.1:8000
Accept: application/json

### GET /hello/{name}
GET http://127.0.0.1:8000/hello/senku
Accept: application/json

### SWAGER documentation
GET http://127.0.0.1:8000/docs
Accept: text/html

### GET /items
GET http://127.0.0.1:8000/items
Accept: application/json

### GET /items/{items_id}
GET http://127.0.0.1:8000/items/5
Accept: application/json

### ERROR /items/{items_id}
GET http://127.0.0.1:8000/items/hello
Accept: application/json

###
GET http://127.0.0.1:8000/users
Accept: application/json

###
GET http://127.0.0.1:8000/users/5
Accept: application/json

###
GET http://127.0.0.1:8000/users/me
Accept: application/json