# https://www.jetbrains.com/help/pycharm/http-client-in-product-code-editor.html

### GET Hello World
GET http://127.0.0.1:8000
Accept: application/json

### GET /hello/{name}
GET http://127.0.0.1:8000/hello/senku
Accept: application/json

### SWAGER documentation
GET http://127.0.0.1:8000/docs
Accept: text/html

### GET /items
GET http://127.0.0.1:8000/items
Accept: application/json

### GET /items/{items_id}
GET http://127.0.0.1:8000/items/5
Accept: application/json

### ERROR /items/{items_id}
GET http://127.0.0.1:8000/items/hello
Accept: application/json

###
GET http://127.0.0.1:8000/users
Accept: application/json

###
GET http://127.0.0.1:8000/users/5
Accept: application/json

###
GET http://127.0.0.1:8000/users/me
Accept: application/json

###
GET http://127.0.0.1:8000/users/bob
Accept: application/json

###
GET http://127.0.0.1:8000/foods/fruits
Accept: application/json

###
GET http://127.0.0.1:8000/foods/vegetables
Accept: application/json

###
GET http://127.0.0.1:8000/foods/dairy
Accept: application/json

### ERROR
GET http://127.0.0.1:8000/foods/meet
Accept: application/json

### GET /items/{items_id}
GET http://127.0.0.1:8000/items/hello?q=word&short=no
Accept: application/json

### GET /items/{items_id}
GET http://127.0.0.1:8000/items/hello?q=word&short=yes
Accept: application/json

### GET /items/{items_id}
GET http://127.0.0.1:8000/items/hello?q=word&short=0
Accept: application/json

### GET /items/{items_id}
GET http://127.0.0.1:8000/items/hello?q=word&short=1
Accept: application/json

###
GET http://127.0.0.1:8000/items/123/item/1234?q=word&short=0
Accept: application/json

###
GET http://127.0.0.1:8000/items?q=12
Accept: application/json

###
GET http://127.0.0.1:8000/items?q=12345678901
Accept: application/json

###
GET http://127.0.0.1:8000/items?required_query=123&q=123&query_list=a&query_list=b&query_list=c&query_list=d
Accept: application/json

###
GET http://127.0.0.1:8000/items_hidden
Accept: application/json

###
GET http://127.0.0.1:8000/items_hidden?hidden_query=123
Accept: application/json

###
PUT http://127.0.0.1:8000/items/12?q=2
Content-Type: application/json

{
  "item": {"name": "string","description": "string","price": 10,"tax": 2},
  "user": {"username": "username","full_name": "full_name"}
}